name: Update Packages

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */4 * * *
  watch:
    types: started

env:
  REPO_URL: github.com/haiibo/openwrt-packages
  REPO_BRANCH: master
  SCRIPT: packages.sh
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set Git Identity
      run : |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        sudo timedatectl set-timezone "$TZ"

    - name: Sync Upstream Update
      run: |
        chmod +x $SCRIPT
        git clone --depth=1 -b $REPO_BRANCH https://$REPO_URL
        REPO_DIR=$(echo $REPO_URL | awk -F '/' '{print $NF}')
        cd $REPO_DIR
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf $(find ./* -maxdepth 0 -type d ! -name ".github") >/dev/null 2>&1
        $GITHUB_WORKSPACE/$SCRIPT
        echo "FILE_PATH=$PWD" >> $GITHUB_ENV

    - name: Push Update to Github
      run: |
        [ -e LICENSE ] && cp LICENSE $FILE_PATH
        [ -e README.md ] && cp README.md $FILE_PATH
        cd $FILE_PATH
        git add .
        git commit -m "Update $(date +%Y-%m-%d" "%H:%M:%S)"
        git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@$REPO_URL" HEAD:$REPO_BRANCH

    - name: Delete Old Workflows
      if: (!cancelled())
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        retain_days: 3
        keep_minimum_runs: 0
